enum GedString: String {
    // Common
    case appName = "app_name"
    case next = "next"
    case back = "back"
    case cancel = "cancel"
    case ok = "ok"
    case delete = "delete"
    case edit = "edit"
    case save = "save"
    case now = "now"
    case finish = "finish"
    case minutesAgoShort = "minutes_ago_short"
    case hoursAgoShort = "hours_ago_short"
    case daysAgoShort = "days_ago_short"
    case weeksAgoShort = "weeks_ago_short"
    case minutesAgoLong = "minutes_ago_long"
    case hoursAgoLong = "hours_ago_long"
    case daysAgoLong = "days_ago_long"
    case weeksAgoLong = "weeks_ago_long"
    case today = "today"
    case yesterday = "yesterday"
    case home = "home"

    // Common errors
    case emptyInputsError = "empty_inputs_error"
    case timedOutError = "timed_out_error"
    case notConnectedToInternetError = "not_connected_to_internet_error"
    
    // Authentication
    case authenticationPageTitle = "authentication_page_title"
    case authenticationPageSubtitle = "authentication_page_subtitle"
    case firstName = "first_name"
    case lastName = "last_name"
    case email = "email"
    case password = "password"
    case login = "login"
    case logout = "logout"
    case register = "register"
    case registration = "registration"
    case notRegisterYet = "not_register_yet"
    case forgottenPassword = "forgotten_password"
    case registrationStep = "registration_step"
    case selectSchoolLevel = "select_school_level"
    case level = "level"
    case enterFirstNameAndLastName = "enter_first_name_and_last_name"
    case enterEmailPassword = "enter_email_password"
    case emailVerificationTitle = "email_verification_title"
    case emailVerificationExplanationBegining = "email_verification_explanation_begining"
    case emailVerificationExplanationEnd = "email_verification_explanation_end"
    case sendEmailVerificationCaption = "send_email_verification_caption"
    case emailNotVerified = "email_not_verified"
    case emailNotVerifiedDialogMessage = "email_not_verified_dialog_message"
    case verifyEmail = "verify_email"
    case logoutAlertMessage = "logout_alert_message"
    
    // Authentication errors
    case invalidEmailError = "invalid_email_error"
    case passwordLengthError = "password_length_error"
    case invalidCredentials = "invalid_credentials"
    case userDisabled = "user_disabled"
    case authUserNotFound = "auth_user_not_found"
    case userNotExist = "user_not_exist"
    case emailNotVerifiedError = "email_not_verified_error"
    case registrationError = "registration_error"
    case accountAlreadyInUseError = "account_already_in_use_error"
    case unknownError = "unknown_error"
    case tooManyRequestError = "too_many_request_error"
    
    // News
    case news = "news"
    case recentAnnouncements = "recent_announcements"
    case newAnnouncement = "new_announcement"
    case editAnnouncement = "edit_announcement"
    case title = "title"
    case content = "content"
    case post = "post"
    case announcementCreated = "announcement_created"
    case noAnnouncement = "no_announcement"
    case deleteAnnouncementAlertMessage = "delete_announcemment_alert_message"
    
    // News errors
    case errorCreatingAnnouncement = "error_creating_announcement"
    case errorDeletingAnnouncement = "error_deleting_announcement"
    
    // Profile
    case profile = "profile"
    case accountInfos = "account_infos"
    case schoolLevel = "school_level"
    case editProfile = "edit_profile"
    case newProfilePicture = "new_profile_picture"
    case profilePictureUpdated = "profile_picture_updated"
    
    // Profile errors
    case errorLogout = "error_logout"
    
    // Message
    case messages = "messages"
    case noUserFound = "no_user_found"
    case tapToChat = "tap_to_chat"
    case messagePlaceholder = "message_placeholder"
    case newConversation = "new_conversation"
    case noConversation = "no_conversation"
    case deleteConversationAlertMessage = "delete_conversation_alert_message"
    case seen = "seen"
    
    // Message errors
    case errorGettingConversations = "error_getting_conversations"
    case errorCreatingConversation = "error_creating_conversation"
    case errorDeletingConversation = "error_deleting_conversation"
}
