enum GedString: String {
    // Common
    case appName = "app_name"
    case next = "next"
    case back = "back"
    case cancel = "cancel"
    case ok = "ok"
    case delete = "delete"
    case edit = "edit"
    case save = "save"
    case now = "now"
    case finish = "finish"
    case resend = "resend"
    case loading = "loading"
    case send = "send"
    case minutesAgoShort = "minutes_ago_short"
    case hoursAgoShort = "hours_ago_short"
    case daysAgoShort = "days_ago_short"
    case weeksAgoShort = "weeks_ago_short"
    case today = "today"
    case yesterday = "yesterday"
    case home = "home"
    case sending = "sending"
    
    // Common errors
    case mandatoryFieldError = "mandatory_field_error"
    case emptyInputsError = "empty_inputs_error"
    case emptyInputError = "empty_input_error"
    case timeOutError = "time_out_error"
    case noInternetConectionError = "no_internet_connection_error"
    case internalServerError = "internal_server_error"
    case unknownError = "unknown_error"
    case unknownNetworkError = "unknown_network_error"
    case userNotFoundError = "user_not_found_error"
    
    // Authentication
    case authenticationPageTitle = "authentication_page_title"
    case authenticationPageSubtitle = "authentication_page_subtitle"
    case firstName = "first_name"
    case lastName = "last_name"
    case email = "email"
    case password = "password"
    case login = "login"
    case logout = "logout"
    case register = "register"
    case registration = "registration"
    case notRegisterYet = "not_register_yet"
    case forgotPassword = "forgot_password"
    case forgotPasswordDescription = "forgot_password_description"
    case registrationStep = "registration_step"
    case selectSchoolLevel = "select_school_level"
    case level = "level"
    case enterNames = "enter_names"
    case enterEmailPassword = "enter_email_password"
    case logoutAlertTitle = "logout_alert_title"
    case forgotPasswordSuccess = "forgot_password_success"
    case userNotWhiteListedError = "user_not_white_listed_error"
    
    // Authentication errors
    case invalidEmailError = "invalid_email_error"
    case passwordLengthError = "password_length_error"
    case invalidCredentials = "invalid_credentials"
    case userDisabled = "user_disabled"
    case authUserNotFound = "auth_user_not_found"
    case userNotExist = "user_not_exist"
    case emailAlreadyAssociatedError = "email_already_associated_error"
    case tooManyRequestsError = "too_many_requests_error"
    case userNotConnected = "user_not_connected"
    
    // News
    case news = "news"
    case announcement = "announcement"
    case recentAnnouncements = "recent_announcements"
    case newAnnouncement = "new_announcement"
    case editAnnouncement = "edit_announcement"
    case title = "title"
    case content = "content"
    case post = "post"
    case announcementCreated = "announcement_created"
    case noAnnouncement = "no_announcement"
    case deleteAnnouncementAlertTitle = "delete_announcement_alert_title"
    
    // News errors
    case announcement_refresh_error = "announcement_refresh_error"
    
    // Profile
    case profile = "profile"
    case accountInfos = "account_infos"
    case schoolLevel = "school_level"
    case editProfile = "edit_profile"
    case newProfilePicture = "new_profile_picture"
    case profilePictureUpdated = "profile_picture_updated"
    case member = "member"
    case userNotFound = "user_not_found"
    case deleteProfilePictureAlertMessage = "delete_profile_picture_alert_message"

    // Profile errors
    case errorLogout = "error_logout"
    
    // Message
    case messages = "messages"
    case tapToChat = "tap_to_chat"
    case messagePlaceholder = "message_placeholder"
    case newConversation = "new_conversation"
    case noConversation = "no_conversation"
    case deleteConversationAlertMessage = "delete_conversation_alert_message"
    case seen = "seen"
    case newMessages = "new_messages"
    
    // Message errors
    case errorGettingConversations = "error_getting_conversations"
    case errorCreatingConversation = "error_creating_conversation"
    case errorDeletingConversation = "error_deleting_conversation"
}
